name: Analyze Terraform Commits

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to analyze (leave empty for all branches)'
        required: false
        type: string
        default: ''
      days:
        description: 'Number of days to analyze (leave empty for all time)'
        required: false
        type: number
        default: 730

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run analysis
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        GITHUB_BRANCH: ${{ inputs.branch }}
        ANALYSIS_DAYS: ${{ inputs.days }}
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python src/main.py
        echo "=================================================="
        echo "Analysis Results:"
        echo "=================================================="
        cat terraform_usage_report.json | jq -r '
          "Owner: \(.owner.name) (\(.owner.type))",
          "Analysis period: \(.analysis_period.start_date) to \(.analysis_period.end_date)",
          "Total repositories analyzed: \(.total_repositories)",
          "Active repositories: \(.active_repositories)",
          "Total Terraform commits: \(.total_commits)",
          "Average monthly commits: \(.average_monthly_commits)",
          "Predicted commits next month: \(.predictions.monthly) (Confidence: \(.predictions.confidence))",
          "Predicted commits next year: \(.predictions.annual) (Confidence: \(.predictions.confidence))",
          "\nMonthly Breakdown:",
          (.monthly_breakdown | to_entries | .[] | "- \(.key): \(.value) commits"),
          "\nActive Repositories:",
          (.repository_details.active | .[] | "- \(.name): \(.total_commits) commits (avg: \(.average_monthly) commits/month)"),
          "\nInactive Repositories (excluded from predictions):",
          (.repository_details.inactive | join(", ")),
          "\nPrediction Factors:",
          "- Historical trend: \(.predictions.factors.historical_trend) commits/month",
          "- Growth rate: \(.predictions.factors.growth_rate * 100)%",
          "- Data variance: \(.predictions.factors.variance)"
        '
